- name: Log Rotation Implementation for custom-monitor
  hosts: sre-log-rotate
  become: true

  vars:
    log_dir: /var/log/custom-monitor
    logrotate_conf_file: /etc/logrotate.d/custom-monitor
    size_limit_mb: 500

  tasks:
    # 1. Ensure the log directory exists
    - name: Ensure log directory {{ log_dir }} exists
      ansible.builtin.file:
        path: "{{ log_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      tags:
        - directory

    # 2. Deploy the custom logrotate configuration file
    - name: Deploy custom logrotate configuration for custom-monitor
      ansible.builtin.template:
        src: files/custom-monitor.conf.j2
        dest: "{{ logrotate_conf_file }}"
        owner: root
        group: root
        mode: '0644'
      tags:
        - config

    # 3. Fail the playbook(skipped when doing --check)
    - name: Fail if exceeds > 500mb
      when: not ansible_check_mode
      ansible.builtin.command: "du -s --block-size=M {{ log_dir }} | awk '{print $1}'"
      register: du_result
      changed_when: false

    - name: set a fact for mb size
      ansible.builtin.set_fact:
        dir_size_mb: "{{ du_result.stdout | regex_replace('M', '') | int }}"
        when: du_result.stdout | length > 0

    - name: fail with error
      ansible.builtin.fail:
        msg: > 
          Exceeding 500MB
      when: dir_size_mb > size_limit_mb
