- name: Log Rotation Implementation for custom-monitor
  hosts: sre-log-rotate
  become: true

  vars:
    log_dir: /var/log/custom-monitor
    logrotate_conf_file: /etc/logrotate.d/custom-monitor

  tasks:
    # 1. Ensure the log directory exists
    - name: Ensure log directory {{ log_dir }} exists
      ansible.builtin.file:
        path: "{{ log_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      tags:
        - directory

    # 2. Deploy the custom logrotate configuration file
    - name: Deploy custom logrotate configuration for custom-monitor
      ansible.builtin.template:
        src: files/custom-monitor.conf.j2
        dest: "{{ logrotate_conf_file }}"
        owner: root
        group: root
        mode: '0644'
      tags:
        - config

    # 3. Validation
    - name: Validate the deployed logrotate configuration (optional dry-run)
      ansible.builtin.command:
        cmd: "logrotate -d {{ logrotate_conf_file }}"
      register: logrotate_check
      changed_when: false